// <auto-generated />
using System;
using Asthani.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asthani.Model.Migrations
{
    [DbContext(typeof(AsthaniDbContext))]
    [Migration("20230210174655_eigth")]
    partial class eigth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asthani.Model.QueueModel.Queue", b =>
                {
                    b.Property<Guid>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EstimateTimeForBooking")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QueNumber")
                        .HasColumnType("int");

                    b.HasKey("QueueId");

                    b.HasIndex("Id");

                    b.ToTable("Queue");
                });

            modelBuilder.Entity("Asthani.Model.TableBookingFormModel.TableHolderInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfFamilyMembers")
                        .HasColumnType("int");

                    b.Property<string>("TableHolderName")
                        .HasColumnType("VarChar(50)");

                    b.HasKey("Id");

                    b.ToTable("TableHolderInfo");
                });

            modelBuilder.Entity("Asthani.Model.TableModel.Table", b =>
                {
                    b.Property<Guid>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("TableNumber")
                        .HasColumnType("VarChar(50)");

                    b.HasKey("TableId");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("Asthani.Model.QueueModel.Queue", b =>
                {
                    b.HasOne("Asthani.Model.TableBookingFormModel.TableHolderInfo", "TableHolderInfo")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableHolderInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
